### ISSUE TITLE
Working on Pi checklist

### ISSUE THREAD

**Issue by kh9sd** [AerospaceNU/better-engine-control-software#24]
- [x] Run `ecs_pi`
- [x] Verify serial port reading works
- [x] Verify valve actuation works
- [x] Verify CRC checking impl works
- [x] Verify sequences run
- [x] Verify integrates/works with some GUI
- [x] Update calibrations
